name: ng2_state
description: A Dart app that uses Angular 2
version: 0.1.0
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  angular: ^4.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  dorm: ^1.0.37
  lawndart: ^0.9.0
dev_dependencies:
  code_transformers: ^0.5.0
  build_runner: ^0.5.0
  source_gen: ^0.7.0
  ng2_form_components:
    git: git@github.com:frankpepermans/ng2_form_components.git
dependency_overrides:
  ng2_form_components:
    path: ../ng2_form_components
  dorm:
    path: ../../../igindo/dart/dorm
transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter