name: ng2_state
description: A Dart app that uses Angular 2
version: 0.2.0
environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha+11
  dorm: ^1.0.37
dev_dependencies:
  build: ^0.12.0
  source_gen: ^0.8.0
  build_runner: ^0.8.7
  build_test: ^0.10.0
  build_web_compilers: ^0.3.7
  ng2_form_components:
    git: git@github.com:frankpepermans/ng2_form_components.git
web:
  compiler:
    debug: dartdevc