name: ng2_state
description: A Dart app that uses Angular 2
version: 0.2.0
environment:
  sdk: '>=2.0.0-dev.62.0 <3.0.0'
dependencies:
  angular: ^5.0.0-beta+2
  dorm: ^1.0.37
  tuple: ^1.0.0
  rxdart: ^0.18.1
dev_dependencies:
  test: ^1.3.0
  build: ^0.12.7
  source_gen: ^0.8.3
  build_runner: ^0.9.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.1
  ng2_form_components:
    git: git@github.com:frankpepermans/ng2_form_components.git
  built_dorm:
    git: git@github.com:frankpepermans/built_dorm.git
web:
  compiler:
    debug: dartdevc